apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-status-service-frontend
  namespace: fint-core
spec:
  port: 8000
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-core-status-service-frontend:latest
  env:
    - name: PUBLIC_API_URL
      value: http://fint-core-status-service:8080
  ingress:
    routes:
      - host: core-status.fintlabs.no
        path: /beta