apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-status-service-frontend
  namespace: fint-core
  labels:
    app.kubernetes.io/name: fint-core-status-service-frontend
    app.kubernetes.io/instance: fint-core-status-service-frontend_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8000
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-core-status-service-frontend:latest
  env:
    - name: PUBLIC_API_URL
      value: https://core-status.fintlabs.no/api
  ingress:
    routes:
      - host: core-status.fintlabs.no
        path: /
        middlewares:
          - fint-core-status-sso