apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-core-status-service-frontend
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-core-status-service-frontend
    app.kubernetes.io/instance: fint-core-status-service-frontend_fintlabs_no
    app.kubernetes.io/component: frontend
spec:
  port: 8000
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-core-status-service-frontend:latest
  url:
    hostname: kunde-beta.felleskomponent.no
    basePath: /status
  ingress:
    enabled: true
    middlewares:
      - fint-core-status-service-sso